version: '3'
services:
  app:
    build: .
    env_file: .env

  rutty:
    image: yantene/rutty
    depends_on:
      - dind
    ports:
      - 3000:3000
    environment:
      REDIS_URL: "redis://redis:6379"
      DOCKER_HOST: "tcp://dind:2375"
  dind:
    image: docker:20.10.2-dind
    environment:
      DOCKER_TLS_CERTDIR: ""
    privileged: true
  redis:
    image: redis:6.0.10-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
